### ISSUE TITLE
CSS not supported anymore

### ISSUE THREAD

**Issue by roydekleijn** [fhoeben/hsac-fitnesse-appium#5]
In the test we use `name=onboarding.button.continue`

I get the message:

```
[debug] [W3C] Calling AppiumDriver.findElements() with args: ["css selector","*[name='onboarding.button.continue']","751dbf6b-fbc9-4c2c-a821-79cda18520f9"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[error] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
```

First step is to upgrade the appium version, see pull-request

**Comment by fhoeben** [comment]
In what context did you get the error? Clicking, retrieving value, ....?

**Comment by fhoeben** [comment]
CSS selector never worked for Appium. Everywhere in 'normal' (browser) codebase where it was used and I encountered it, I disabled it for Appium.
You hit a code path I did not consider/hit before. But I have to say I'm surprised since you are selecting by technical selector name...

**Comment by fhoeben** [comment]
Do you have a stack trace to go with this message?

**Comment by fhoeben** [comment]
That stack trace does not match the css selector issue you started this thread with....

This stack trace indicates that a list of elements is returned where a single web element was expected.... 
`org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {element-6066-11e4-a52e-4f735466cecf=D800DB38-D5E0-4D34-9DCB-AE09C0894232}
`
`Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to org.openqa.selenium.WebElement`

**Comment by roydekleijn** [comment]
appium server shows:
```

[debug] [W3C] Calling AppiumDriver.findElements() with args: ["css selector","*[name='onboarding.button.continue']","751dbf6b-fbc9-4c2c-a821-79cda18520f9"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[error] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
```

at the same time. So I do think it's related somehow

**Comment by fhoeben** [comment]
Then it must be the server converting a 'name' to a css, and then that not working...

I suspect it's an Appium bug. Can you debug the code (put a breakpoint and see what `By` we are sending)?

**Comment by fhoeben** [comment]
https://github.com/appium/appium/issues/11338
