### ISSUE TITLE
Interacting with androidElement throws NPE on isEnabled/isVisible/etc.

### ISSUE THREAD

**Issue by tcnh** [fhoeben/hsac-fitnesse-appium#6]
As I can't seem to find a related issue in the appium java client repo, I suspect this to be releated to the fixture code.

When trying to interact (i.e. wait for visible, click) on any element in android, a NPE is thrown when determining the visibility of an element:

`java.lang.NullPointerException
 at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
 at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
 at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
 at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
 at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:317)
 at nl.hsac.fitnesse.fixture.util.mobile.element.HsacAndroidElement.lambda$new$0(HsacAndroidElement.java:17)
 at nl.hsac.fitnesse.fixture.util.selenium.caching.BooleanCache.getNewBooleanValue(BooleanCache.java:65)
 at nl.hsac.fitnesse.fixture.util.selenium.caching.BooleanCache.getBooleanValue(BooleanCache.java:27)
 at nl.hsac.fitnesse.fixture.util.mobile.element.HsacAndroidElement.isDisplayed(HsacAndroidElement.java:49)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.scrollIfNotOnScreen(BrowserTest.java:1536)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitForVisibleIn(BrowserTest.java:1000)
 at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitForVisible(BrowserTest.java:991)`

The element however, is present and returned by the appium server.

**Comment by fhoeben** [comment]
I don't see how this can be a problem in the fixtures. The method that is called does not accept any parameters, so it is a problem internally somewhere. Maybe a version problem between the API used by the fixtures and the appium server?

@roydekleijn did you ever encounter this?

**Comment by tcnh** [comment]
I'm using 0.0.10 (appium v 6.1.0) with appium server 1.9.1. I'll see if I can lower the appium server version number. (Lowering the api version or fixtures version introduces some class casting issues due to selenium version conflicts)

**Comment by tcnh** [comment]
It seems that the AndroidDriver coming from AndroidTest's getMobileHelper().driver() is somehow different then when we create it without appium driver setup.

This simple test works:
`package nl.hsac.fitnesse.fixture.slim.mobile;
        
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.MalformedURLException;
import java.net.URL;

public class VanillaAppium {


    public AndroidDriver<AndroidElement> driver;
    public WebDriverWait wait;


    @Before
    public void setup () throws MalformedURLException {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("deviceName", "ce011821904b90d50c");
        caps.setCapability("platformName", "Android");
        caps.setCapability("platformVersion", "8.0.0");
        caps.setCapability("appPackage", "com.takeaway.android");
        caps.setCapability("appActivity","com.takeaway.android.activity.RestaurantListActivity");
        driver = new AndroidDriver<AndroidElement>(new URL("http://0.0.0.0:4723/wd/hub"),caps);
        wait = new WebDriverWait(driver, 10);
    }


    @Test
    public void basicTest () throws InterruptedException {
        //Click and pass Splash
        wait.until(ExpectedConditions.visibilityOfElementLocated
                (By.xpath("//*[@text='TOESTAAN']"))).click();



    }

    @After
    public void teardown(){
        driver.quit();
    }

}
`

if we create `driver` using appium driver setup's connectToAndroidDriverAtWithCapabilities, any AndroidElement gets Nulled

**Comment by fhoeben** [comment]
Looking at the stack trace, it shows that the problem is that the element created by `createAndroidElement()` does not have a parent.
That was indeed a problem in my code. 

I'm building 0.11.0 now.....

**Comment by fhoeben** [comment]
Thanks for the report, and detailed analysis. Please re-open if the issue remains in 0.0.11
